---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nominatim.zebernst.dev
  resources:
  - nominatimoperations
  - nominatims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nominatim.zebernst.dev
  resources:
  - nominatimoperations/finalizers
  - nominatims/finalizers
  verbs:
  - update
- apiGroups:
  - nominatim.zebernst.dev
  resources:
  - nominatimoperations/status
  - nominatims/status
  verbs:
  - get
  - patch
  - update
