apiVersion: nominatim.zebernst.dev/v1alpha1
kind: Nominatim
metadata:
  labels:
    app.kubernetes.io/name: nominatim-operator
    app.kubernetes.io/managed-by: kustomize
  name: nominatim-sample
spec:
  project:
    volume:
      claimName: nominatim-project
  regions:
    - north-america/us
  regionChangePolicy: AddData
  database:
    clusterRef:
      name: nominatim-pg
  updates:
    enabled: true
    schedule: "0 3 * * *"
  api:
    replicas: 1
    suspendDuringOperations: Never
